#!/bin/sh
mkdir -p /sys
mkdir -p /proc
mkdir -p /dev
mkdir -p /root
mkdir -p /mnt
mount -t sysfs none /sys
mount -t proc none /proc
mount -t devtmpfs none /dev
for c in `cat /proc/cmdline`; do	
	case $c in
		root=*)
			ROOT=`echo $c | sed 's/root=//'`;;
		init=*)
			init=`echo $c | sed 's/init=//'`;;
	esac
done
if [ -z "$ROOT" ]; then
	exec /bin/sh
fi
mount -o ro $ROOT /root
if [ -z "$init" ]; then
	init=/sbin/init
fi
if [ -n "$subdir" ]; then
	mount /root/$subdir /mnt
	exec chroot /mnt $init
fi
if [ -n "$rootimg" ]; then
	mount -o remount,rw /root
	mount /root/$rootimg /mnt
	exec chroot /mnt $init
fi
exec chroot /root $init
